language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - python -m unittest discover -v

deploy:
  provider: pypi
  skip_existing: true
  user: ondro
  password:
    secure: PvA9eVk8GIWzPtxXDreJ7lSCZWL11C2u1groJwuchWmmKxK6U0Woi5d04MQGd2WPNP4KJKxCRo2xnSVRCBR7nLoUCecnL8/Ox8RLMarI7tR5tLDIQI2z2lQRJfZvY6WRPSi0qibtZXiQh8ySu3FTnI3PPlwFFyDJR2N0QSDyo7+F1b+q5jc6X3a4WI4nVY0pu4iCi9CssGsREd+i9/2ZOBzq8g23mvnhAHHYQh8Ry0L/BMEYoctnETouZ2A5Glr3Q7WY7x2f8MUNK62tK+UBuc9Et5EAXV3/5JPWG0DxfNMlo33F+63L0FMAVGQiC7Gubl1Ggdgd7mGltnNSjd/Z1lYbxE7yMZ6PfIiEpnhxHrvVcyDs5DZ2Hw3oLpWGGxEJ+xH+VIw0YWhriUxt+EBQBigGIJTJISheYMm72KqopZ95FHT2HPNUxkVrqbxgLlgs8svmf2kJWP02QriaIzhFvxVJ4H5FZ0e5GgK0ZJWGfgQY6hOtR3qSKPdGULrH4h0Kw5U9DaXjFStTE7AHQJ9uvozJvnOQ5behPV89Dng/aP6YGDwmjoLWebSF6BT+YsOp5JNmBM0TaeakBOpIHPaT1SWClV5uDG7NDgDxH8g01b6n+0XLi/+c/mCflRzQO+3NDS5v3XaklgoFnVAzrFvyYbsUq2ITdFD5Az/MFYmw2Bk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
    python: '3.6'

notifications:
  email:
    - lexa.ondrej@gmail.com

