name: polylx
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - pyarrow
  - seaborn
  - networkx
  - shapely>=2
  - pyshp
  - flake8
  - pytest
  - pyefd
  - jenkspy
  - shapelysmooth
