# run: conda env create --file environment.yml
name: polylx
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - networkx
  - shapely>=2
  - pyshp
  - fiona
  - pip:
    - pyefd
